/* ============================================================
 * data.js — 連續水洗能耗計算工具：查表資料 / 雙語字典
 * 這個檔案只放「資料」，不放邏輯。修改物理常數預設值、熱源熱值/排碳係數、
 * 雙語字串時改這裡；改計算邏輯或畫面互動去改 app.js。
 * 載入順序要排在 app.js 之前（app.js 會直接使用這裡定義的常數）。
 * ============================================================ */

/* ============================================================
   翻譯字典
   ============================================================ */
const TRANSLATIONS = {
  zh: {
    appTitle: "連續水洗機能耗計算器",
    tabSettings: "自定義",
    tabProcess: "水洗流程",
    tabResults: "計算結果",
    tabMethods: "計算方式",
    customSettingsTitle: "自定義參數設置",
    customSettingsSub: "物理常數與機台設定，一般不需調整；有特殊現場條件才需要修改",
    heatSourceLabel: "熱源選擇",
    heavyOil: "重油",
    coal: "煤炭",
    naturalGas: "天然氣",
    carbonFactorLabel: "燃料碳排放因子 (kg CO₂/kg)",
    fuelHeatValueLabel: "燃料熱值 (kJ/kg)",
    electricityCarbonFactorLabel: "電力碳排放因子 (kg CO₂/kWh)",
    steamLatentHeatLabel: "蒸汽潛熱 (kJ/kg)",
    boilerEfficiencyLabel: "鍋爐效率 (%)",
    preheatingTimeLabel: "熱機時間 (分鐘)",
    baseLoadPowerLabel: "基本負載功率 (kW)",
    singleDrumPowerLabel: "單鼓洗滌室增量功率 (kW)",
    doubleDrumPowerLabel: "雙鼓洗滌室增量功率 (kW)",
    stackedWashPowerLabel: "堆疊洗滌室增量功率 (kW)",
    heatRecoveryEfficiencyLabel: "熱回收效率 (%)",
    insulationFactorLabel: "設備保溫係數 (0-1)",
    resetDefaultsBtn: "重設為預設值",
    processSettingsTitle: "水洗流程設置",
    loadSetLabel: "載入流程組",
    saveSetLabel: "儲存流程組",
    addProcessBtn: "＋ 新增水洗流程",
    clearBtn: "清除",
    selectSetOpt: "-- 選擇已儲存的流程組 --",
    setNamePh: "輸入流程組名稱",
    deleteBtn: "刪除",
    saveBtn: "儲存",
    processNameDefault: "流程",
    fabricSpeedLabel: "進布速度 (m/min)",
    fabricWeightLabel: "布重 (g/m)",
    fabricLengthLabel: "布匹總長度 (m)",
    hotWaterTempLabel: "進水熱水溫度 (°C)",
    coldWaterTempLabel: "進水冷水溫度 (°C)",
    unitsTitle: "處理單元",
    addUnitBtn: "＋ 新增單元",
    firstUnitLabel: "第一處理單元（固定）",
    unitLabel: "處理單元",
    finalColdUnitLabel: "最終冷水單元（固定）",
    unitTypeLabel: "單元類型",
    singleDrum: "單鼓洗滌室",
    doubleDrum: "雙鼓洗滌室",
    stackedWash: "堆疊洗滌室",
    waterRatioLabel: "用水比 (L/kg)",
    recycleRatioLabel: "提供給前一單元的回流水比例 (%)",
    recycledWaterTempLabel: "回流水溫度 (°C)",
    targetTempLabel: "目標溫度 (°C)",
    sprayCountLabel: "噴淋數量",
    processTimeLabel: "處理時間 (分鐘)",
    sprayTempLabel: "噴淋 {i} 溫度 (°C)",
    resultsTitle: "計算結果",
    calcBtn: "計算 / 更新結果",
    waterCompareTitle: "每公斤布水消耗 (L/kg)",
    energyCompareTitle: "能耗和碳排放比較圖 (每公斤布料)",
    totalConsumptionCol: "總消耗量",
    perKgCol: "每公斤消耗量",
    waterResultLabel: "總用水量",
    thermalResultLabel: "熱能消耗",
    electricityResultLabel: "電力消耗",
    steamResultLabel: "蒸汽消耗",
    fuelResultLabel: "燃料消耗",
    electricityCarbonLabel: "電力碳排放",
    fuelCarbonLabel: "燃料碳排放",
    carbonResultLabel: "總碳排放",
    timeResultLabel: "總處理時間",
    processParametersSummary: "流程參數概述",
    unitCol: "單元",
    tempCol: "溫度",
    waterRatioCol: "用水比",
    recycleRatioCol: "回流比",
    freshWaterCol: "新水用量",
    noProcessesMsg: "還沒有流程資料，請先到「水洗流程」新增流程。",
    methodsTitle: "計算方式說明",
    m_preheatTitle: "熱機階段",
    m_preheatLines: [
      "1. 電力消耗 = 設備總功率 × 熱機時間",
      "2. 熱能消耗 = 所有單元所需熱水量 × 比熱容 × (進水熱水溫度 − 進水冷水溫度) ÷ 3600"
    ],
    m_chainTitle: "水洗流程階段（從最後一個單元開始，逐步向前計算）",
    m_chainLines: [
      "1. 總水量 = 用水比 × 布重 × 布匹長度",
      "2. 可用回流水量 = 後一個單元所提供的回流水量 (後一單元總水量 × 提供給前一單元的回流水比例 (%))",
      "3. 新鮮進水量 = 總水量 − 可用回流水量",
      "4. 混合水溫 = (新鮮進水量 × 進水熱水溫度 + 回流水量 × 回流水溫) ÷ 總水量",
      "5. 如果混合水溫 < 目標溫度，計算加熱能耗",
      "6. 如果是堆疊洗滌室，考慮額外的處理時間"
    ],
    m_heatingTitle: "最後一道冷水單元",
    m_heatingLines: [
      "使用冷水，不需加熱，但納入回流水計算"
    ],
    m_timeTitle: "總能耗計算",
    m_timeLines: [
      "總電力消耗 = 熱機電力消耗 + 水洗流程電力消耗",
      "總熱能消耗 = (熱機熱能消耗 + 水洗流程加熱能耗) × (1 − 熱回收效率) ÷ 保溫係數",
      "蒸汽消耗 = 總熱能消耗 ÷ (蒸汽潛熱 × 鍋爐效率)",
      "燃料消耗 = 蒸汽消耗 × 蒸汽潛熱 ÷ (燃料熱值 × 鍋爐效率)",
      "電力碳排放 = 總電力消耗 × 電力碳排放因子",
      "燃料碳排放 = 燃料消耗 × 燃料碳排放因子",
      "總碳排放 = 電力碳排放 + 燃料碳排放"
    ],
    m_totalTitle: "常數與轉換因子",
    m_totalLines: [
      "水的比熱容：4.186 kJ/(kg·°C)",
      "重油熱值：40194 kJ/kg ｜ 煤炭熱值：29307 kJ/kg ｜ 天然氣熱值：38931 kJ/kg",
      "能源熱值為低位熱值 (LHV, Lower Heating Value)，即淨熱值，不包括水蒸氣冷凝所釋放的熱量",
      "重油碳排放因子：3.15 kg CO₂/kg ｜ 煤炭：2.86 kg CO₂/kg ｜ 天然氣：2.03 kg CO₂/kg"
    ]
  },
  en: {
    appTitle: "Continuous Washing Machine Energy Calculator",
    tabSettings: "Settings",
    tabProcess: "Wash Lines",
    tabResults: "Results",
    tabMethods: "Methods",
    customSettingsTitle: "Custom Parameters",
    customSettingsSub: "Physical constants & machine settings — usually no need to adjust unless site conditions differ",
    heatSourceLabel: "Heat Source:",
    heavyOil: "Heavy Oil",
    coal: "Coal",
    naturalGas: "Natural Gas",
    carbonFactorLabel: "Fuel Carbon Factor (kg CO₂/kg):",
    fuelHeatValueLabel: "Fuel Heat Value (kJ/kg):",
    electricityCarbonFactorLabel: "Electricity Carbon Factor (kg CO₂/kWh):",
    steamLatentHeatLabel: "Steam Latent Heat (kJ/kg):",
    boilerEfficiencyLabel: "Boiler Efficiency (%):",
    preheatingTimeLabel: "Preheating Time (min):",
    baseLoadPowerLabel: "Base Load Power (kW):",
    singleDrumPowerLabel: "Single Drum Power (kW):",
    doubleDrumPowerLabel: "Double Drum Power (kW):",
    stackedWashPowerLabel: "Stacked Wash Power (kW):",
    heatRecoveryEfficiencyLabel: "Heat Recovery Efficiency (%):",
    insulationFactorLabel: "Insulation Factor (0-1):",
    resetDefaultsBtn: "Reset to Defaults",
    processSettingsTitle: "Washing Process Settings",
    loadSetLabel: "Load Saved",
    saveSetLabel: "Save Process",
    addProcessBtn: "+ Add Process",
    clearBtn: "Clear",
    selectSetOpt: "-- Select a saved process --",
    setNamePh: "Enter process name",
    deleteBtn: "Delete",
    saveBtn: "Save",
    processNameDefault: "Process",
    fabricSpeedLabel: "Fabric Speed (m/min):",
    fabricWeightLabel: "Fabric Weight (g/m):",
    fabricLengthLabel: "Fabric Length (m):",
    hotWaterTempLabel: "Hot Water Temp (°C):",
    coldWaterTempLabel: "Cold Water Temp (°C):",
    unitsTitle: "Units",
    addUnitBtn: "+ Add Unit",
    firstUnitLabel: "First Unit (Fixed)",
    unitLabel: "Unit",
    finalColdUnitLabel: "Final Cold Unit",
    unitTypeLabel: "Unit Type:",
    singleDrum: "Single Drum",
    doubleDrum: "Double Drum",
    stackedWash: "Stacked Wash",
    waterRatioLabel: "Water Ratio (L/kg):",
    recycleRatioLabel: "Recycle Ratio (%):",
    recycledWaterTempLabel: "Recycled Water Temp (°C):",
    targetTempLabel: "Target Temp (°C):",
    sprayCountLabel: "Spray Count:",
    processTimeLabel: "Process Time (min):",
    sprayTempLabel: "Spray {i} Temp (°C):",
    resultsTitle: "Results",
    calcBtn: "Calculate",
    waterCompareTitle: "Water Consumption (L/kg)",
    energyCompareTitle: "Energy & Carbon (per kg fabric)",
    totalConsumptionCol: "Total",
    perKgCol: "Per kg Fabric",
    waterResultLabel: "Total Water",
    thermalResultLabel: "Thermal Energy",
    electricityResultLabel: "Electricity",
    steamResultLabel: "Steam",
    fuelResultLabel: "Fuel",
    electricityCarbonLabel: "Electricity Carbon",
    fuelCarbonLabel: "Fuel Carbon",
    carbonResultLabel: "Total Carbon",
    timeResultLabel: "Total Time",
    processParametersSummary: "Process Summary",
    unitCol: "Unit",
    tempCol: "Temp",
    waterRatioCol: "Water Ratio",
    recycleRatioCol: "Recycle Ratio",
    freshWaterCol: "Fresh Water",
    noProcessesMsg: "No valid results. Check input data.",
    methodsTitle: "Calculation Methods",
    m_preheatTitle: "Preheating Stage",
    m_preheatLines: [
      "1. Electricity = Total Equipment Power × Preheating Time",
      "2. Thermal Energy = Total Water Required × Heat Capacity × (Hot Water Temp − Cold Water Temp) ÷ 3600"
    ],
    m_chainTitle: "Washing Process Stage (calculated backward from the last unit)",
    m_chainLines: [
      "1. Total Water = Water Ratio × Fabric Weight × Fabric Length",
      "2. Available Recycled Water = Water provided by the next unit (Total Water of next unit × Recycle Ratio (%))",
      "3. Fresh Water = Total Water − Available Recycled Water",
      "4. Mixed Water Temp = (Fresh Water × Hot Water Temp + Recycled Water × Recycled Temp) ÷ Total Water",
      "5. If Mixed Water Temp < Target Temp, calculate heating energy required",
      "6. If Stacked Wash, account for additional process time"
    ],
    m_heatingTitle: "Final Cold Water Unit",
    m_heatingLines: [
      "Uses cold water, no heating required, but included in recycled water calculations"
    ],
    m_timeTitle: "Total Energy Calculation",
    m_timeLines: [
      "Total Electricity = Preheating Electricity + Process Electricity",
      "Total Thermal Energy = (Preheating Thermal + Process Heating Energy) × (1 − Heat Recovery Efficiency) ÷ Insulation Factor",
      "Steam = Total Thermal Energy ÷ (Steam Latent Heat × Boiler Efficiency)",
      "Fuel = Steam × Steam Latent Heat ÷ (Fuel Heat Value × Boiler Efficiency)",
      "Electricity Carbon = Total Electricity × Electricity Carbon Factor",
      "Fuel Carbon = Fuel × Fuel Carbon Factor",
      "Total Carbon = Electricity Carbon + Fuel Carbon"
    ],
    m_totalTitle: "Constants & Conversion Factors",
    m_totalLines: [
      "Water Heat Capacity: 4.186 kJ/(kg·°C)",
      "Heavy Oil Heat Value: 40194 kJ/kg ｜ Coal: 29307 kJ/kg ｜ Natural Gas: 38931 kJ/kg",
      "Heating values are Lower Heating Value (LHV), excluding condensation heat of water vapor",
      "Heavy Oil Carbon Factor: 3.15 kg CO₂/kg ｜ Coal: 2.86 kg CO₂/kg ｜ Natural Gas: 2.03 kg CO₂/kg"
    ]
  }
};

/* ---- 物理常數預設值 ---- */
const DEFAULT_SETTINGS = {
  heatSource: "heavyOil",
  carbonFactor: 3.15,
  fuelHeatValue: 40194,
  electricityCarbonFactor: 0.5,
  steamLatentHeat: 2257,
  boilerEfficiency: 80,
  preheatingTime: 30,
  baseLoadPower: 15,
  singleDrumPower: 3,
  doubleDrumPower: 5,
  stackedWashPower: 7,
  heatRecoveryEfficiency: 30,
  insulationFactor: 0.95
};

/* ---- 熱源熱值 / 排碳係數預設組合 ---- */
const HEAT_SOURCE_PRESETS = {
  heavyOil: { fuelHeatValue: 40194, carbonFactor: 3.15 },
  coal: { fuelHeatValue: 29307, carbonFactor: 2.86 },
  naturalGas: { fuelHeatValue: 38931, carbonFactor: 2.03 }
};
